package main.testmasterbot.state;

public enum SessionState {
    IDLE,
    WAITING_TEST_TITLE,
    WAITING_TEST_DESCRIPTION,
    WAITING_QUESTION_TEXT,
    WAITING_OPTION_TEXT,
    WAITING_CORRECT_TEXT_ANSWER,
    WAITING_CORRECT_NUMBER_ANSWER,
    WAITING_QUESTION_PHOTO,
    WAITING_EDIT_TITLE,
    WAITING_EDIT_DESCRIPTION,
    WAITING_ADMIN_ADD_MODERATOR,
    WAITING_ADMIN_ADD_ADMIN,
    WAITING_ADMIN_REMOVE_ROLE
}
